package sweetpos;

//import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.*;
//import java.awt.Color;
//import java.awt.Font;
import java.sql.*;
//import java.sql.Connection;
//import java.sql.ResultSet;
//import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
//import java.sql.DriverManager;
//import java.sql.SQLException;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javaswingdev.drawer.Drawer;
import javaswingdev.drawer.DrawerController;
import javaswingdev.drawer.DrawerItem;
import javaswingdev.drawer.EventDrawer;

public class products extends javax.swing.JFrame {

    /**
     * Creates new form category
     */
    private DrawerController drawer;
    String name1;
    
    public products(String name) {
        initComponents();
        table_update();
        getDrawer();
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        category();
        this.name1 = name;
        nameLabel.setText(name);
    }
    
    Connection con1;
    PreparedStatement pst;
    
    //Retrieves the id and name of category
    public class CategoryItem {
        int id;
        String name;
        public CategoryItem(int id, String name) {
            this.id = id;
            this.name = name;
        }
        public String toString(){
            return name;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        catLabel = new javax.swing.JLabel();
        staLabel = new javax.swing.JLabel();
        txtstat = new javax.swing.JComboBox<>();
        addButton1 = new javax.swing.JButton();
        deleteButton1 = new javax.swing.JButton();
        updateButton1 = new javax.swing.JButton();
        txtproduct = new javax.swing.JTextField();
        catLabel1 = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        catLabel2 = new javax.swing.JLabel();
        txtcategory = new javax.swing.JComboBox();
        txtprice = new javax.swing.JTextField();
        catLabel3 = new javax.swing.JLabel();
        catLabel4 = new javax.swing.JLabel();
        txtdateadd = new javax.swing.JTextField();
        catLabel5 = new javax.swing.JLabel();
        txtdateexp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        menuButton.setBackground(new java.awt.Color(255, 255, 255));
        menuButton.setForeground(new java.awt.Color(255, 255, 255));
        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuIcon.png"))); // NOI18N
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Milky Nice", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Category", "Product Name", "Quantity", "Price", "Status", "Date Added", "Expiry Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        catLabel.setFont(new java.awt.Font("Milky Nice", 0, 24)); // NOI18N
        catLabel.setForeground(new java.awt.Color(50, 80, 255));
        catLabel.setText("Category:");

        staLabel.setFont(new java.awt.Font("Milky Nice", 0, 24)); // NOI18N
        staLabel.setForeground(new java.awt.Color(50, 80, 255));
        staLabel.setText("Status:");

        txtstat.setFont(new java.awt.Font("Milky Nice", 0, 12)); // NOI18N
        txtstat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Not Active" }));

        addButton1.setBackground(new java.awt.Color(50, 80, 255));
        addButton1.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        addButton1.setForeground(new java.awt.Color(255, 255, 255));
        addButton1.setText("+ Add Product");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        deleteButton1.setBackground(new java.awt.Color(255, 75, 85));
        deleteButton1.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        deleteButton1.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton1.setText("X Delete Product");
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });

        updateButton1.setBackground(new java.awt.Color(50, 80, 255));
        updateButton1.setFont(new java.awt.Font("Milky Nice", 0, 14)); // NOI18N
        updateButton1.setForeground(new java.awt.Color(255, 255, 255));
        updateButton1.setText("Update Product");
        updateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton1ActionPerformed(evt);
            }
        });

        txtproduct.setFont(new java.awt.Font("Milky Nice", 0, 12)); // NOI18N
        txtproduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        catLabel1.setFont(new java.awt.Font("Milky Nice", 0, 24)); // NOI18N
        catLabel1.setForeground(new java.awt.Color(50, 80, 255));
        catLabel1.setText("Product Name:");

        txtquantity.setFont(new java.awt.Font("Milky Nice", 0, 12)); // NOI18N
        txtquantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        catLabel2.setFont(new java.awt.Font("Milky Nice", 0, 24)); // NOI18N
        catLabel2.setForeground(new java.awt.Color(50, 80, 255));
        catLabel2.setText("Quantity:");

        txtcategory.setFont(new java.awt.Font("Milky Nice", 0, 12)); // NOI18N

        txtprice.setFont(new java.awt.Font("Milky Nice", 0, 12)); // NOI18N
        txtprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        catLabel3.setFont(new java.awt.Font("Milky Nice", 0, 24)); // NOI18N
        catLabel3.setForeground(new java.awt.Color(50, 80, 255));
        catLabel3.setText("Price:");

        catLabel4.setFont(new java.awt.Font("Milky Nice", 0, 24)); // NOI18N
        catLabel4.setForeground(new java.awt.Color(50, 80, 255));
        catLabel4.setText("Date Added:");

        txtdateadd.setFont(new java.awt.Font("Milky Nice", 0, 12)); // NOI18N
        txtdateadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        catLabel5.setFont(new java.awt.Font("Milky Nice", 0, 24)); // NOI18N
        catLabel5.setForeground(new java.awt.Color(50, 80, 255));
        catLabel5.setText("Expiry Date:");

        txtdateexp.setFont(new java.awt.Font("Milky Nice", 0, 12)); // NOI18N
        txtdateexp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(catLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(catLabel3)
                            .addComponent(catLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(catLabel5)
                                .addComponent(catLabel4)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(txtproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtprice)
                                    .addComponent(txtdateadd)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(txtdateexp)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(catLabel)
                            .addComponent(staLabel))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcategory, 0, 300, Short.MAX_VALUE)
                            .addComponent(txtstat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(deleteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(catLabel1)
                            .addComponent(txtproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtcategory, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(catLabel, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(catLabel2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(catLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtstat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(staLabel))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(catLabel4)
                            .addComponent(txtdateadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(catLabel5)
                            .addComponent(txtdateexp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jLabel1.setFont(new java.awt.Font("Milky Nice", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Products");

        nameLabel.setFont(new java.awt.Font("Milky Nice", 0, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(50, 80, 255));
        nameLabel.setText(" ");
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    //Retrieves the id and name of category in the database
    private void category() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/sweetdb","root","");
            pst = con1.prepareStatement("select * from category");
            ResultSet rs = pst.executeQuery();
            txtcategory.removeAllItems();
            while (rs.next()){
                txtcategory.addItem(new CategoryItem(rs.getInt(1),rs.getString(2)));
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(products.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void table_update() {
        try {
            int c;
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/sweetdb","root","");
                pst = con1.prepareStatement("select * from products");
                ResultSet rs = pst.executeQuery();
                
                ResultSetMetaData rsd = rs.getMetaData();
                c = rsd.getColumnCount();
                
                DefaultTableModel d = (DefaultTableModel)jTable1.getModel();
                d.setRowCount(0);
                jTable1.setDefaultEditor(Object.class, null);
                
                JTableHeader tableHeader = jTable1.getTableHeader();
                tableHeader.setBackground(Color.white);
                tableHeader.setForeground(Color.black);
                Font headerFont = new Font("Milky Nice", Font.PLAIN, 14);
                tableHeader.setFont(headerFont);
                
                while(rs.next()) {
                    Vector v2 = new Vector();
                    for (int i = 1; i<=c; i++) {
                        v2.add(rs.getString("product_id"));
                        v2.add(rs.getString("category"));
                        v2.add(rs.getString("product_name"));
                        v2.add(rs.getString("quantity"));
                        v2.add(rs.getString("price"));
                        v2.add(rs.getString("status"));
                        v2.add(rs.getString("date_added"));
                        v2.add(rs.getString("expiry_date"));
                    }
                    d.addRow(v2);
                }
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void getDrawer() {
        drawer = Drawer.newDrawer(this)
                .header(new Header())
                .space(30)
                .background(new Color(185,210,250))
                .backgroundTransparent(0.3f)
                .drawerWidth(300)
                .duration(200)
                .enableScroll(true)
                .drawerBackground(new Color(185,210,250))
                
                .addChild(new DrawerItem("Category")
                        .icon(new ImageIcon(getClass().getResource("/icons/Category.gif")))
                        .font(new Font("Milky Nice", Font.PLAIN, 14))
                        .build())
                .addChild(new DrawerItem("Products")
                        .icon(new ImageIcon(getClass().getResource("/icons/Cookie.gif")))
                        .font(new Font("Milky Nice", Font.PLAIN, 14))
                        .build())
                .addChild(new DrawerItem("Inventory")
                        .icon(new ImageIcon(getClass().getResource("/icons/Inventory.gif")))
                        .font(new Font("Milky Nice", Font.PLAIN, 14))
                        .build())
                .addChild(new DrawerItem("Release of Items")
                        .icon(new ImageIcon(getClass().getResource("/icons/releaseItem.gif")))
                        .font(new Font("Milky Nice", Font.PLAIN, 14))
                        .build())
                .addChild(new DrawerItem("  Point of Sales")
                        .icon(new ImageIcon(getClass().getResource("/icons/Receipt.gif")))
                        .font(new Font("Milky Nice", Font.PLAIN, 14))
                        .build())
                .addFooter(new DrawerItem("Exit")
                        .icon(new ImageIcon(getClass().getResource("/icons/exitIcon.png")))
                        .font(new Font("Milky Nice", Font.PLAIN, 14))
                        .build())
                        .event(new EventDrawer() {
                            @Override
                            public void selected(int index, DrawerItem item) {
                                if (item.getLabel().equals("Category")) {
                                    products.this.setVisible(false);
                                    category c = new category(name1);
                                    c.setVisible(true);
                                }
                                if (item.getLabel().equals("Inventory")) {
                                    products.this.setVisible(false);
                                    inventory i = new inventory(name1);
                                    i.setVisible(true);
                                }
                                if (item.getLabel().equals("Release of Items")) {
                                    products.this.setVisible(false);
                                    roi o = new roi(name1);
                                    o.setVisible(true);
                                }
                                if (item.getLabel().equals("  Point of Sales")) {
                                    products.this.setVisible(false);
                                    pos p = new pos(name1);
                                    p.setVisible(true);
                                }
                                if (item.getLabel().equals("Exit")) {
                                    int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to exit the program?", "Warning", JOptionPane.YES_NO_OPTION);
                                    if (dialogResult == JOptionPane.YES_OPTION) {
                                    System.exit(0);
                                    }
                                }
                        }
                })
                .build();
    }
    
    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        if(drawer.isShow()) {
            drawer.hide();
        } else {
            drawer.show();
        }
    }//GEN-LAST:event_menuButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        
        txtcategory.setSelectedItem(d1.getValueAt(selectIndex, 1).toString());
        txtproduct.setText(d1.getValueAt(selectIndex, 2).toString());
        txtquantity.setText(d1.getValueAt(selectIndex, 3).toString());
        txtprice.setText(d1.getValueAt(selectIndex, 4).toString());
        txtstat.setSelectedItem(d1.getValueAt(selectIndex, 5).toString());
        txtdateadd.setText(d1.getValueAt(selectIndex, 6).toString());
        txtdateexp.setText(d1.getValueAt(selectIndex, 7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        CategoryItem item = (CategoryItem)txtcategory.getSelectedItem();
        String product_name = txtproduct.getText();
        String quantity = txtquantity.getText();
        String price = txtprice.getText();
        String status = txtstat.getSelectedItem().toString();
        String date_added = txtdateadd.getText();
        String expiry_date = txtdateexp.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/sweetdb","root","");
            pst = con1.prepareStatement("insert into products(category,product_name,quantity,price,status,date_added,expiry_date)values(?,?,?,?,?,?,?)");
            pst.setString(1, item.name);
            pst.setString(2, product_name);
            pst.setString(3, quantity);
            pst.setString(4, price);
            pst.setString(5, status);
            pst.setString(6, date_added);
            pst.setString(7, expiry_date);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Product successfully added!");
            table_update();
            txtcategory.setSelectedIndex(-1);
            txtproduct.setText("");
            txtquantity.setText("");
            txtprice.setText("");
            txtstat.setSelectedIndex(-1);
            txtdateadd.setText("");
            txtdateexp.setText("");
            txtproduct.requestFocus();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addButton1ActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to delete the record?", "Warning", JOptionPane.YES_NO_OPTION);

        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/sweetdb","root","");
                pst = con1.prepareStatement("delete from products where product_id = ?");
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Product successfully deleted!");
                table_update();
                txtcategory.setSelectedIndex(-1);
                txtproduct.setText("");
                txtquantity.setText("");
                txtprice.setText("");
                txtstat.setSelectedIndex(-1);
                txtdateadd.setText("");
                txtdateexp.setText("");
                txtproduct.requestFocus();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteButton1ActionPerformed

    private void updateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButton1ActionPerformed
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        int product_id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
        CategoryItem item = (CategoryItem)txtcategory.getSelectedItem();
        String product_name = txtproduct.getText();
        String quantity = txtquantity.getText();
        String price = txtprice.getText();
        String status = txtstat.getSelectedItem().toString();
        String date_added = txtdateadd.getText();
        String expiry_date = txtdateexp.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/sweetdb","root","");
            pst = con1.prepareStatement("update products set category = ?, product_name = ?, quantity = ?, price = ?, status = ?, date_added = ?, expiry_date = ? where product_id = ?");
            pst.setString(1, item.name);
            pst.setString(2, product_name);
            pst.setString(3, quantity);
            pst.setString(4, price);
            pst.setString(5, status);
            pst.setString(6, date_added);
            pst.setString(7, expiry_date);
            pst.setInt(8, product_id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Product successfully updated!");
            table_update();
            txtcategory.setSelectedIndex(-1);
            txtproduct.setText("");
            txtquantity.setText("");
            txtprice.setText("");
            txtstat.setSelectedIndex(-1);
            txtdateadd.setText("");
            txtdateexp.setText("");
            txtproduct.requestFocus();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButton1ActionPerformed
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton1;
    private javax.swing.JLabel catLabel;
    private javax.swing.JLabel catLabel1;
    private javax.swing.JLabel catLabel2;
    private javax.swing.JLabel catLabel3;
    private javax.swing.JLabel catLabel4;
    private javax.swing.JLabel catLabel5;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel staLabel;
    private javax.swing.JComboBox txtcategory;
    private javax.swing.JTextField txtdateadd;
    private javax.swing.JTextField txtdateexp;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtproduct;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JComboBox<String> txtstat;
    private javax.swing.JButton updateButton1;
    // End of variables declaration//GEN-END:variables
}
